ALTER TYPE partner_category ADD VALUE IF NOT EXISTS 'driver';
ALTER TYPE partner_category ADD VALUE IF NOT EXISTS 'translator';

ALTER TABLE partner_profiles
  ADD COLUMN IF NOT EXISTS full_name_th text,
  ADD COLUMN IF NOT EXISTS full_name_en text,
  ADD COLUMN IF NOT EXISTS nickname text,
  ADD COLUMN IF NOT EXISTS age int,
  ADD COLUMN IF NOT EXISTS id_number text,
  ADD COLUMN IF NOT EXISTS date_of_birth date,
  ADD COLUMN IF NOT EXISTS nationality text,
  ADD COLUMN IF NOT EXISTS phone text,
  ADD COLUMN IF NOT EXISTS line_id text,
  ADD COLUMN IF NOT EXISTS wechat_id text,
  ADD COLUMN IF NOT EXISTS contact_email text,
  ADD COLUMN IF NOT EXISTS address text,
  ADD COLUMN IF NOT EXISTS province text,
  ADD COLUMN IF NOT EXISTS postcode text,
  ADD COLUMN IF NOT EXISTS languages jsonb DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS skills text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS service_styles text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS special_routes text,
  ADD COLUMN IF NOT EXISTS bank_name text,
  ADD COLUMN IF NOT EXISTS bank_branch text,
  ADD COLUMN IF NOT EXISTS account_name text,
  ADD COLUMN IF NOT EXISTS account_number text,
  ADD COLUMN IF NOT EXISTS account_type text,
  ADD COLUMN IF NOT EXISTS promptpay text,
  ADD COLUMN IF NOT EXISTS guide_license_no text,
  ADD COLUMN IF NOT EXISTS guide_license_type text,
  ADD COLUMN IF NOT EXISTS marital_status text,
  ADD COLUMN IF NOT EXISTS education jsonb DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS certifications text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS work_experience jsonb DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS driving_license_type text,
  ADD COLUMN IF NOT EXISTS driving_license_no text,
  ADD COLUMN IF NOT EXISTS driving_license_expiry date,
  ADD COLUMN IF NOT EXISTS vehicle_brand text,
  ADD COLUMN IF NOT EXISTS vehicle_color text,
  ADD COLUMN IF NOT EXISTS vehicle_plate text,
  ADD COLUMN IF NOT EXISTS vehicle_plate_province text,
  ADD COLUMN IF NOT EXISTS vehicle_year int,
  ADD COLUMN IF NOT EXISTS vehicle_seats int,
  ADD COLUMN IF NOT EXISTS vehicle_plate_type text,
  ADD COLUMN IF NOT EXISTS vehicle_insurance_compulsory text,
  ADD COLUMN IF NOT EXISTS vehicle_insurance_compulsory_expiry date,
  ADD COLUMN IF NOT EXISTS vehicle_insurance_voluntary text,
  ADD COLUMN IF NOT EXISTS passport_no text,
  ADD COLUMN IF NOT EXISTS education_level text,
  ADD COLUMN IF NOT EXISTS education_major text,
  ADD COLUMN IF NOT EXISTS translation_pairs jsonb DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS test_scores jsonb DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS translation_specializations text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS translator_tools jsonb DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS daily_capacity text,
  ADD COLUMN IF NOT EXISTS rate_per_word text,
  ADD COLUMN IF NOT EXISTS working_hours text,
  ADD COLUMN IF NOT EXISTS rush_job_available boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS terms_accepted boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS terms_accepted_at timestamptz;
